### ISSUE TITLE
疫情地图打开变成空白页

### ISSUE THREAD

**Issue by zby-66** [LiangWuCode/2019-nCoV#1]
疫情地图打开变成空白页

**Comment by LiangWuCode** [comment]
可将api那个项目部署到服务器 &nbsp; &nbsp;目前首页的数据调用的是api那个项目的接口。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiangWuCode/2019-nCoV"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 中午11:17
收件人:&nbsp;"LiangWuCode/2019-nCoV"<2019-nCoV@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[LiangWuCode/2019-nCoV] 疫情地图打开变成空白页 (#1)





 
疫情地图打开变成空白页

**Comment by zby-66** [comment]
好滴
